/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import newpackage.loginform;
import javax.swing.JFrame;

/**
 *
 * @author Jitca David
 */
public class singup extends javax.swing.JFrame {

    /**
     * Creates new form singup
     */
    public singup() {
        initComponents();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        UserNameField = new javax.swing.JTextField();
        jLabelMail = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        MailField = new javax.swing.JTextField();
        PassWordField = new javax.swing.JPasswordField();
        jLabelPASS = new javax.swing.JLabel();
        CancelButton = new javax.swing.JButton();
        LoginCLick = new javax.swing.JLabel();
        jLabelMinimize = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        SingupButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sing up");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(208, 225, 249));
        jPanel1.setForeground(new java.awt.Color(77, 100, 141));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(40, 54, 85));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jitca David\\Desktop\\network.png")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ChessGame by MasterMinds");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 0, 460);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sing Up");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(300, 50, 120, 60);

        UserNameField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        UserNameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(UserNameField);
        UserNameField.setBounds(290, 300, 190, 40);

        jLabelMail.setBackground(new java.awt.Color(77, 100, 141));
        jLabelMail.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabelMail.setForeground(new java.awt.Color(40, 54, 85));
        jLabelMail.setText("Mail");
        jPanel1.add(jLabelMail);
        jLabelMail.setBounds(290, 130, 44, 16);

        jLabelName.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(40, 54, 85));
        jLabelName.setText("User Name");
        jPanel1.add(jLabelName);
        jLabelName.setBounds(290, 280, 70, 16);

        MailField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        MailField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MailFieldActionPerformed(evt);
            }
        });
        jPanel1.add(MailField);
        MailField.setBounds(290, 150, 190, 40);

        PassWordField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        PassWordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PassWordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassWordFieldActionPerformed(evt);
            }
        });
        jPanel1.add(PassWordField);
        PassWordField.setBounds(290, 220, 190, 40);

        jLabelPASS.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabelPASS.setForeground(new java.awt.Color(40, 54, 85));
        jLabelPASS.setText("Login Password");
        jPanel1.add(jLabelPASS);
        jLabelPASS.setBounds(290, 200, 100, 16);

        CancelButton.setBackground(new java.awt.Color(77, 100, 141));
        CancelButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        CancelButton.setForeground(new java.awt.Color(40, 54, 85));
        CancelButton.setText("Cancel");
        CancelButton.setBorder(null);
        CancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CancelButton);
        CancelButton.setBounds(300, 370, 70, 30);

        LoginCLick.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        LoginCLick.setForeground(new java.awt.Color(40, 54, 85));
        LoginCLick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginCLick.setText("Already register Click here to login");
        LoginCLick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginCLick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginCLickMouseClicked(evt);
            }
        });
        jPanel1.add(LoginCLick);
        LoginCLick.setBounds(290, 420, 200, 16);

        jLabelMinimize.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabelMinimize.setForeground(new java.awt.Color(40, 54, 85));
        jLabelMinimize.setText("-");
        jLabelMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMinimize);
        jLabelMinimize.setBounds(490, 10, 20, 20);

        jLabelClose.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(40, 54, 85));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelClose);
        jLabelClose.setBounds(520, 10, 20, 20);

        SingupButton.setBackground(new java.awt.Color(77, 100, 141));
        SingupButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        SingupButton.setForeground(new java.awt.Color(40, 54, 85));
        SingupButton.setText("Sing up");
        SingupButton.setBorder(null);
        SingupButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SingupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SingupButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SingupButton);
        SingupButton.setBounds(410, 370, 70, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MailFieldActionPerformed

    private void PassWordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassWordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassWordFieldActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        MailField.setText(null);
        UserNameField.setText(null);
        PassWordField.setText(null);
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
            System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseClicked

    private void SingupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SingupButtonActionPerformed
        String nume;
        String parola;
        String mail;
               
    }//GEN-LAST:event_SingupButtonActionPerformed

    private void LoginCLickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginCLickMouseClicked
        loginform lgf = new loginform();
        lgf.setVisible(true);
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_LoginCLickMouseClicked

    /**
     * @param args
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(singup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(singup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(singup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(singup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new singup().setVisible(true);
                
            }
        });
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel LoginCLick;
    private javax.swing.JTextField MailField;
    private javax.swing.JPasswordField PassWordField;
    private javax.swing.JButton SingupButton;
    private javax.swing.JTextField UserNameField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMail;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPASS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
